version: "3.9"
services:
  web:
    container_name: app-nextjs
    image: perporserot/nextjs-docker
    restart: unless-stopped
    build: .
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test?authSource=admin
    env_file:
      - .env
    links:
      - postgres
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./database.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'
    user: "501:20"
    env_file:
      - .env
  smtp-server:
    image: reachfive/fake-smtp-server:latest
    restart: unless-stopped
    ports:
      - 1025:1025